
sudo: true
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
install:
  - apt-get install net-tools
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
