
sudo: true
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
before_install:
  - apt-get -qq update
  - apt-get install -y net-tools
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
